name: Checks
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - '*'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  gradle:
    runs-on: macOS-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache Gradle Caches
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-clean-gradle-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-clean-wrapper-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Run detekt
        run: ./gradlew detektAll

      - name: Run tests
        run: ./gradlew :sentinel:testDebugUnitTest

      # We stop gradle at the end to make sure the cache folders
      # don't contain any lock files and are free to be cached.
      - name: Stop Gradle
        run: ./gradlew --stop