name: Code analysis
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Save Gradle Caches
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches/
          key: gradle-caches-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-caches-${{ runner.os }}-
      - name: Lint
        run: ./gradlew lintAll
      - name: Stop Gradle
        run: ./gradlew --stop

  detekt:
    name: Detekt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Save Gradle Caches
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches/
          key: gradle-caches-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-caches-${{ runner.os }}-
      - name: Detekt
        run: ./gradlew detektAll
      - name: Stop Gradle
        run: ./gradlew --stop

  ktlint:
    name: ktlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Save Gradle Caches
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches/
          key: gradle-caches-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-caches-${{ runner.os }}-
      - name: ktlint
        run: ./gradlew ktlintAll
      - name: Stop Gradle
        run: ./gradlew --stop
  cpd:
    name: CPD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Save Gradle Caches
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches/
          key: gradle-caches-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-caches-${{ runner.os }}-
      - name: CPD
        run: ./gradlew cpdAll
      - name: Stop Gradle
        run: ./gradlew --stop